In [6]:
!aws s3 sync s3://oceanhunter-production-data-warehouse/transformed_data/cold_data/bullet/ ./FM01bullet

download: s3://oceanhunter-production-data-warehouse/transformed_data/cold_data/bullet/year=2025/month=5/day=25/000.parquet to FM01bullet/year=2025/month=5/day=25/000.parquet
download: s3://oceanhunter-production-data-warehouse/transformed_data/cold_data/bullet/year=2025/month=5/day=20/000.parquet to FM01bullet/year=2025/month=5/day=20/000.parquet
download: s3://oceanhunter-production-data-warehouse/transformed_data/cold_data/bullet/year=2025/month=5/day=23/000.parquet to FM01bullet/year=2025/month=5/day=23/000.parquet
download: s3://oceanhunter-production-data-warehouse/transformed_data/cold_data/bullet/year=2025/month=5/day=26/000.parquet to FM01bullet/year=2025/month=5/day=26/000.parquet
download: s3://oceanhunter-production-data-warehouse/transformed_data/cold_data/bullet/year=2025/month=5/day=24/000.parquet to FM01bullet/year=2025/month=5/day=24/000.parquet
download: s3://oceanhunter-production-data-warehouse/transformed_data/cold_data/bullet/year=2025/month=5/day=22/000.parquet to FM01bullet/year=2025/month=5/day=22/000.parquet
download: s3://oceanhunter-production-data-warehouse/transformed_data/cold_data/bullet/year=2025/month=5/day=21/000.parquet to FM01bullet/year=2025/month=5/day=21/000.parquet
download: s3://oceanhunter-production-data-warehouse/transformed_data/cold_data/bullet/year=2025/month=5/day=27/000.parquet to FM01bullet/year=2025/month=5/day=27/000.parquet
download: s3://oceanhunter-production-data-warehouse/transformed_data/cold_data/bullet/year=2025/month=5/day=28/000.parquet to FM01bullet/year=2025/month=5/day=28/000.parquet
download: s3://oceanhunter-production-data-warehouse/transformed_data/cold_data/bullet/year=2025/month=5/day=30/000.parquet to FM01bullet/year=2025/month=5/day=30/000.parquet
download: s3://oceanhunter-production-data-warehouse/transformed_data/cold_data/bullet/year=2025/month=5/day=31/000.parquet to FM01bullet/year=2025/month=5/day=31/000.parquet
download: s3://oceanhunter-production-data-warehouse/transformed_data/cold_data/bullet/year=2025/month=6/day=1/000.parquet to FM01bullet/year=2025/month=6/day=1/000.parquet
download: s3://oceanhunter-production-data-warehouse/transformed_data/cold_data/bullet/year=2025/month=6/day=11/000.parquet to FM01bullet/year=2025/month=6/day=11/000.parquet
download: s3://oceanhunter-production-data-warehouse/transformed_data/cold_data/bullet/year=2025/month=5/day=29/000.parquet to FM01bullet/year=2025/month=5/day=29/000.parquet
download: s3://oceanhunter-production-data-warehouse/transformed_data/cold_data/bullet/year=2025/month=6/day=12/000.parquet to FM01bullet/year=2025/month=6/day=12/000.parquet
download: s3://oceanhunter-production-data-warehouse/transformed_data/cold_data/bullet/year=2025/month=6/day=10/000.parquet to FM01bullet/year=2025/month=6/day=10/000.parquet
download: s3://oceanhunter-production-data-warehouse/transformed_data/cold_data/bullet/year=2025/month=6/day=15/000.parquet to FM01bullet/year=2025/month=6/day=15/000.parquet
download: s3://oceanhunter-production-data-warehouse/transformed_data/cold_data/bullet/year=2025/month=6/day=17/000.parquet to FM01bullet/year=2025/month=6/day=17/000.parquet
download: s3://oceanhunter-production-data-warehouse/transformed_data/cold_data/bullet/year=2025/month=6/day=18/000.parquet to FM01bullet/year=2025/month=6/day=18/000.parquet
download: s3://oceanhunter-production-data-warehouse/transformed_data/cold_data/bullet/year=2025/month=6/day=20/000.parquet to FM01bullet/year=2025/month=6/day=20/000.parquet
download: s3://oceanhunter-production-data-warehouse/transformed_data/cold_data/bullet/year=2025/month=6/day=19/000.parquet to FM01bullet/year=2025/month=6/day=19/000.parquet
download: s3://oceanhunter-production-data-warehouse/transformed_data/cold_data/bullet/year=2025/month=6/day=13/000.parquet to FM01bullet/year=2025/month=6/day=13/000.parquet
download: s3://oceanhunter-production-data-warehouse/transformed_data/cold_data/bullet/year=2025/month=6/day=14/000.parquet to FM01bullet/year=2025/month=6/day=14/000.parquet
download: s3://oceanhunter-production-data-warehouse/transformed_data/cold_data/bullet/year=2025/month=6/day=16/000.parquet to FM01bullet/year=2025/month=6/day=16/000.parquet
download: s3://oceanhunter-production-data-warehouse/transformed_data/cold_data/bullet/year=2025/month=6/day=2/000.parquet to FM01bullet/year=2025/month=6/day=2/000.parquet
download: s3://oceanhunter-production-data-warehouse/transformed_data/cold_data/bullet/year=2025/month=6/day=21/000.parquet to FM01bullet/year=2025/month=6/day=21/000.parquet
download: s3://oceanhunter-production-data-warehouse/transformed_data/cold_data/bullet/year=2025/month=6/day=26/000.parquet to FM01bullet/year=2025/month=6/day=26/000.parquet
download: s3://oceanhunter-production-data-warehouse/transformed_data/cold_data/bullet/year=2025/month=6/day=22/000.parquet to FM01bullet/year=2025/month=6/day=22/000.parquet
download: s3://oceanhunter-production-data-warehouse/transformed_data/cold_data/bullet/year=2025/month=6/day=23/000.parquet to FM01bullet/year=2025/month=6/day=23/000.parquet
download: s3://oceanhunter-production-data-warehouse/transformed_data/cold_data/bullet/year=2025/month=6/day=27/000.parquet to FM01bullet/year=2025/month=6/day=27/000.parquet
download: s3://oceanhunter-production-data-warehouse/transformed_data/cold_data/bullet/year=2025/month=6/day=28/000.parquet to FM01bullet/year=2025/month=6/day=28/000.parquet
download: s3://oceanhunter-production-data-warehouse/transformed_data/cold_data/bullet/year=2025/month=6/day=3/000.parquet to FM01bullet/year=2025/month=6/day=3/000.parquet
download: s3://oceanhunter-production-data-warehouse/transformed_data/cold_data/bullet/year=2025/month=6/day=24/000.parquet to FM01bullet/year=2025/month=6/day=24/000.parquet
download: s3://oceanhunter-production-data-warehouse/transformed_data/cold_data/bullet/year=2025/month=6/day=4/000.parquet to FM01bullet/year=2025/month=6/day=4/000.parquet
download: s3://oceanhunter-production-data-warehouse/transformed_data/cold_data/bullet/year=2025/month=6/day=30/000.parquet to FM01bullet/year=2025/month=6/day=30/000.parquet
download: s3://oceanhunter-production-data-warehouse/transformed_data/cold_data/bullet/year=2025/month=6/day=25/000.parquet to FM01bullet/year=2025/month=6/day=25/000.parquet
download: s3://oceanhunter-production-data-warehouse/transformed_data/cold_data/bullet/year=2025/month=6/day=7/000.parquet to FM01bullet/year=2025/month=6/day=7/000.parquet
download: s3://oceanhunter-production-data-warehouse/transformed_data/cold_data/bullet/year=2025/month=6/day=6/000.parquet to FM01bullet/year=2025/month=6/day=6/000.parquet
download: s3://oceanhunter-production-data-warehouse/transformed_data/cold_data/bullet/year=2025/month=6/day=29/000.parquet to FM01bullet/year=2025/month=6/day=29/000.parquet
download: s3://oceanhunter-production-data-warehouse/transformed_data/cold_data/bullet/year=2025/month=7/day=11/000.parquet to FM01bullet/year=2025/month=7/day=11/000.parquet
download: s3://oceanhunter-production-data-warehouse/transformed_data/cold_data/bullet/year=2025/month=6/day=5/000.parquet to FM01bullet/year=2025/month=6/day=5/000.parquet
download: s3://oceanhunter-production-data-warehouse/transformed_data/cold_data/bullet/year=2025/month=6/day=8/000.parquet to FM01bullet/year=2025/month=6/day=8/000.parquet
download: s3://oceanhunter-production-data-warehouse/transformed_data/cold_data/bullet/year=2025/month=6/day=9/000.parquet to FM01bullet/year=2025/month=6/day=9/000.parquet
download: s3://oceanhunter-production-data-warehouse/transformed_data/cold_data/bullet/year=2025/month=7/day=10/000.parquet to FM01bullet/year=2025/month=7/day=10/000.parquet
download: s3://oceanhunter-production-data-warehouse/transformed_data/cold_data/bullet/year=2025/month=7/day=1/000.parquet to FM01bullet/year=2025/month=7/day=1/000.parquet
download: s3://oceanhunter-production-data-warehouse/transformed_data/cold_data/bullet/year=2025/month=7/day=17/000.parquet to FM01bullet/year=2025/month=7/day=17/000.parquet
download: s3://oceanhunter-production-data-warehouse/transformed_data/cold_data/bullet/year=2025/month=7/day=12/000.parquet to FM01bullet/year=2025/month=7/day=12/000.parquet
download: s3://oceanhunter-production-data-warehouse/transformed_data/cold_data/bullet/year=2025/month=7/day=14/000.parquet to FM01bullet/year=2025/month=7/day=14/000.parquet
download: s3://oceanhunter-production-data-warehouse/transformed_data/cold_data/bullet/year=2025/month=7/day=20/000.parquet to FM01bullet/year=2025/month=7/day=20/000.parquet
download: s3://oceanhunter-production-data-warehouse/transformed_data/cold_data/bullet/year=2025/month=7/day=16/000.parquet to FM01bullet/year=2025/month=7/day=16/000.parquet
download: s3://oceanhunter-production-data-warehouse/transformed_data/cold_data/bullet/year=2025/month=7/day=19/000.parquet to FM01bullet/year=2025/month=7/day=19/000.parquet
download: s3://oceanhunter-production-data-warehouse/transformed_data/cold_data/bullet/year=2025/month=7/day=18/000.parquet to FM01bullet/year=2025/month=7/day=18/000.parquet
download: s3://oceanhunter-production-data-warehouse/transformed_data/cold_data/bullet/year=2025/month=7/day=13/000.parquet to FM01bullet/year=2025/month=7/day=13/000.parquet
download: s3://oceanhunter-production-data-warehouse/transformed_data/cold_data/bullet/year=2025/month=7/day=15/000.parquet to FM01bullet/year=2025/month=7/day=15/000.parquet
download: s3://oceanhunter-production-data-warehouse/transformed_data/cold_data/bullet/year=2025/month=7/day=24/000.parquet to FM01bullet/year=2025/month=7/day=24/000.parquet
download: s3://oceanhunter-production-data-warehouse/transformed_data/cold_data/bullet/year=2025/month=7/day=21/000.parquet to FM01bullet/year=2025/month=7/day=21/000.parquet
download: s3://oceanhunter-production-data-warehouse/transformed_data/cold_data/bullet/year=2025/month=7/day=23/000.parquet to FM01bullet/year=2025/month=7/day=23/000.parquet
download: s3://oceanhunter-production-data-warehouse/transformed_data/cold_data/bullet/year=2025/month=7/day=25/000.parquet to FM01bullet/year=2025/month=7/day=25/000.parquet
download: s3://oceanhunter-production-data-warehouse/transformed_data/cold_data/bullet/year=2025/month=7/day=26/000.parquet to FM01bullet/year=2025/month=7/day=26/000.parquet
download: s3://oceanhunter-production-data-warehouse/transformed_data/cold_data/bullet/year=2025/month=7/day=22/000.parquet to FM01bullet/year=2025/month=7/day=22/000.parquet
download: s3://oceanhunter-production-data-warehouse/transformed_data/cold_data/bullet/year=2025/month=7/day=27/000.parquet to FM01bullet/year=2025/month=7/day=27/000.parquet
download: s3://oceanhunter-production-data-warehouse/transformed_data/cold_data/bullet/year=2025/month=7/day=2/000.parquet to FM01bullet/year=2025/month=7/day=2/000.parquet
download: s3://oceanhunter-production-data-warehouse/transformed_data/cold_data/bullet/year=2025/month=7/day=31/000.parquet to FM01bullet/year=2025/month=7/day=31/000.parquet
download: s3://oceanhunter-production-data-warehouse/transformed_data/cold_data/bullet/year=2025/month=7/day=3/000.parquet to FM01bullet/year=2025/month=7/day=3/000.parquet
download: s3://oceanhunter-production-data-warehouse/transformed_data/cold_data/bullet/year=2025/month=7/day=4/000.parquet to FM01bullet/year=2025/month=7/day=4/000.parquet
download: s3://oceanhunter-production-data-warehouse/transformed_data/cold_data/bullet/year=2025/month=7/day=30/000.parquet to FM01bullet/year=2025/month=7/day=30/000.parquet
download: s3://oceanhunter-production-data-warehouse/transformed_data/cold_data/bullet/year=2025/month=7/day=5/000.parquet to FM01bullet/year=2025/month=7/day=5/000.parquet
download: s3://oceanhunter-production-data-warehouse/transformed_data/cold_data/bullet/year=2025/month=7/day=8/000.parquet to FM01bullet/year=2025/month=7/day=8/000.parquet
download: s3://oceanhunter-production-data-warehouse/transformed_data/cold_data/bullet/year=2025/month=7/day=7/000.parquet to FM01bullet/year=2025/month=7/day=7/000.parquet
download: s3://oceanhunter-production-data-warehouse/transformed_data/cold_data/bullet/year=2025/month=7/day=9/000.parquet to FM01bullet/year=2025/month=7/day=9/000.parquet
download: s3://oceanhunter-production-data-warehouse/transformed_data/cold_data/bullet/year=2025/month=7/day=29/000.parquet to FM01bullet/year=2025/month=7/day=29/000.parquet
download: s3://oceanhunter-production-data-warehouse/transformed_data/cold_data/bullet/year=2025/month=7/day=6/000.parquet to FM01bullet/year=2025/month=7/day=6/000.parquet
download: s3://oceanhunter-production-data-warehouse/transformed_data/cold_data/bullet/year=2025/month=8/day=10/000.parquet to FM01bullet/year=2025/month=8/day=10/000.parquet
download: s3://oceanhunter-production-data-warehouse/transformed_data/cold_data/bullet/year=2025/month=8/day=11/000.parquet to FM01bullet/year=2025/month=8/day=11/000.parquet
download: s3://oceanhunter-production-data-warehouse/transformed_data/cold_data/bullet/year=2025/month=8/day=1/000.parquet to FM01bullet/year=2025/month=8/day=1/000.parquet
download: s3://oceanhunter-production-data-warehouse/transformed_data/cold_data/bullet/year=2025/month=8/day=13/000.parquet to FM01bullet/year=2025/month=8/day=13/000.parquet
download: s3://oceanhunter-production-data-warehouse/transformed_data/cold_data/bullet/year=2025/month=8/day=12/000.parquet to FM01bullet/year=2025/month=8/day=12/000.parquet
download: s3://oceanhunter-production-data-warehouse/transformed_data/cold_data/bullet/year=2025/month=8/day=15/000.parquet to FM01bullet/year=2025/month=8/day=15/000.parquet
download: s3://oceanhunter-production-data-warehouse/transformed_data/cold_data/bullet/year=2025/month=7/day=28/000.parquet to FM01bullet/year=2025/month=7/day=28/000.parquet
download: s3://oceanhunter-production-data-warehouse/transformed_data/cold_data/bullet/year=2025/month=8/day=16/000.parquet to FM01bullet/year=2025/month=8/day=16/000.parquet
download: s3://oceanhunter-production-data-warehouse/transformed_data/cold_data/bullet/year=2025/month=8/day=16/001.parquet to FM01bullet/year=2025/month=8/day=16/001.parquet
download: s3://oceanhunter-production-data-warehouse/transformed_data/cold_data/bullet/year=2025/month=8/day=14/000.parquet to FM01bullet/year=2025/month=8/day=14/000.parquet
download: s3://oceanhunter-production-data-warehouse/transformed_data/cold_data/bullet/year=2025/month=8/day=18/000.parquet to FM01bullet/year=2025/month=8/day=18/000.parquet
download: s3://oceanhunter-production-data-warehouse/transformed_data/cold_data/bullet/year=2025/month=8/day=20/000.parquet to FM01bullet/year=2025/month=8/day=20/000.parquet
download: s3://oceanhunter-production-data-warehouse/transformed_data/cold_data/bullet/year=2025/month=8/day=2/000.parquet to FM01bullet/year=2025/month=8/day=2/000.parquet
download: s3://oceanhunter-production-data-warehouse/transformed_data/cold_data/bullet/year=2025/month=8/day=23/000.parquet to FM01bullet/year=2025/month=8/day=23/000.parquet
download: s3://oceanhunter-production-data-warehouse/transformed_data/cold_data/bullet/year=2025/month=8/day=17/000.parquet to FM01bullet/year=2025/month=8/day=17/000.parquet
download: s3://oceanhunter-production-data-warehouse/transformed_data/cold_data/bullet/year=2025/month=8/day=21/000.parquet to FM01bullet/year=2025/month=8/day=21/000.parquet
download: s3://oceanhunter-production-data-warehouse/transformed_data/cold_data/bullet/year=2025/month=8/day=26/000.parquet to FM01bullet/year=2025/month=8/day=26/000.parquet
download: s3://oceanhunter-production-data-warehouse/transformed_data/cold_data/bullet/year=2025/month=8/day=24/000.parquet to FM01bullet/year=2025/month=8/day=24/000.parquet
download: s3://oceanhunter-production-data-warehouse/transformed_data/cold_data/bullet/year=2025/month=8/day=27/000.parquet to FM01bullet/year=2025/month=8/day=27/000.parquet
download: s3://oceanhunter-production-data-warehouse/transformed_data/cold_data/bullet/year=2025/month=8/day=29/000.parquet to FM01bullet/year=2025/month=8/day=29/000.parquet
download: s3://oceanhunter-production-data-warehouse/transformed_data/cold_data/bullet/year=2025/month=8/day=19/000.parquet to FM01bullet/year=2025/month=8/day=19/000.parquet
download: s3://oceanhunter-production-data-warehouse/transformed_data/cold_data/bullet/year=2025/month=8/day=3/000.parquet to FM01bullet/year=2025/month=8/day=3/000.parquet
download: s3://oceanhunter-production-data-warehouse/transformed_data/cold_data/bullet/year=2025/month=8/day=25/000.parquet to FM01bullet/year=2025/month=8/day=25/000.parquet
download: s3://oceanhunter-production-data-warehouse/transformed_data/cold_data/bullet/year=2025/month=8/day=28/000.parquet to FM01bullet/year=2025/month=8/day=28/000.parquet
download: s3://oceanhunter-production-data-warehouse/transformed_data/cold_data/bullet/year=2025/month=8/day=31/000.parquet to FM01bullet/year=2025/month=8/day=31/000.parquet
download: s3://oceanhunter-production-data-warehouse/transformed_data/cold_data/bullet/year=2025/month=8/day=5/000.parquet to FM01bullet/year=2025/month=8/day=5/000.parquet
download: s3://oceanhunter-production-data-warehouse/transformed_data/cold_data/bullet/year=2025/month=8/day=22/000.parquet to FM01bullet/year=2025/month=8/day=22/000.parquet
download: s3://oceanhunter-production-data-warehouse/transformed_data/cold_data/bullet/year=2025/month=8/day=30/000.parquet to FM01bullet/year=2025/month=8/day=30/000.parquet
download: s3://oceanhunter-production-data-warehouse/transformed_data/cold_data/bullet/year=2025/month=8/day=7/000.parquet to FM01bullet/year=2025/month=8/day=7/000.parquet
download: s3://oceanhunter-production-data-warehouse/transformed_data/cold_data/bullet/year=2025/month=8/day=6/000.parquet to FM01bullet/year=2025/month=8/day=6/000.parquet
download: s3://oceanhunter-production-data-warehouse/transformed_data/cold_data/bullet/year=2025/month=9/day=10/000.parquet to FM01bullet/year=2025/month=9/day=10/000.parquet
download: s3://oceanhunter-production-data-warehouse/transformed_data/cold_data/bullet/year=2025/month=9/day=1/000.parquet to FM01bullet/year=2025/month=9/day=1/000.parquet
download: s3://oceanhunter-production-data-warehouse/transformed_data/cold_data/bullet/year=2025/month=8/day=8/000.parquet to FM01bullet/year=2025/month=8/day=8/000.parquet
download: s3://oceanhunter-production-data-warehouse/transformed_data/cold_data/bullet/year=2025/month=9/day=11/000.parquet to FM01bullet/year=2025/month=9/day=11/000.parquet
download: s3://oceanhunter-production-data-warehouse/transformed_data/cold_data/bullet/year=2025/month=8/day=4/000.parquet to FM01bullet/year=2025/month=8/day=4/000.parquet
download: s3://oceanhunter-production-data-warehouse/transformed_data/cold_data/bullet/year=2025/month=8/day=9/000.parquet to FM01bullet/year=2025/month=8/day=9/000.parquet
download: s3://oceanhunter-production-data-warehouse/transformed_data/cold_data/bullet/year=2025/month=9/day=13/000.parquet to FM01bullet/year=2025/month=9/day=13/000.parquet
download: s3://oceanhunter-production-data-warehouse/transformed_data/cold_data/bullet/year=2025/month=9/day=16/000.parquet to FM01bullet/year=2025/month=9/day=16/000.parquet
download: s3://oceanhunter-production-data-warehouse/transformed_data/cold_data/bullet/year=2025/month=9/day=14/000.parquet to FM01bullet/year=2025/month=9/day=14/000.parquet
download: s3://oceanhunter-production-data-warehouse/transformed_data/cold_data/bullet/year=2025/month=9/day=12/000.parquet to FM01bullet/year=2025/month=9/day=12/000.parquet
download: s3://oceanhunter-production-data-warehouse/transformed_data/cold_data/bullet/year=2025/month=9/day=15/000.parquet to FM01bullet/year=2025/month=9/day=15/000.parquet
download: s3://oceanhunter-production-data-warehouse/transformed_data/cold_data/bullet/year=2025/month=9/day=19/000.parquet to FM01bullet/year=2025/month=9/day=19/000.parquet

In [8]:
!aws s3 sync s3://platform-production-data-warehouse/transformed_data/cold_data/dim_game_auth_user_latest/ ./FM01player

download: s3://platform-production-data-warehouse/transformed_data/cold_data/dim_game_auth_user_latest/000.parquet to FM01player/000.parquet

In [9]:
import os
import glob
import pandas as pd
import concurrent.futures

BASE_PATH = "./FM01bullet/year=2025/month=8/"   # 你的 8 月 parquet 路径

# 递归查找所有 parquet 文件
parquet_files = glob.glob(os.path.join(BASE_PATH, "day=*/**/*.parquet"), recursive=True)
print(f"找到 {len(parquet_files)} 个 parquet 文件")

def load_parquet(file_path):
    """读取单个 parquet 文件"""
    try:
        return pd.read_parquet(file_path)
    except Exception as e:
        print(f"❌ 读取失败 {file_path}: {e}")
        return pd.DataFrame()

# 多线程读取
dfs = []
with concurrent.futures.ThreadPoolExecutor(max_workers=8) as executor:  # 8 个线程，可调
    futures = {executor.submit(load_parquet, f): f for f in parquet_files}
    for future in concurrent.futures.as_completed(futures):
        df = future.result()
        if not df.empty:
            dfs.append(df)

# 合并成一个 DataFrame
final_df = pd.concat(dfs, ignore_index=True)

print(f"合并完成，DataFrame 形状: {final_df.shape}")

找到 32 个 parquet 文件
合并完成，DataFrame 形状: (9858639, 34)

In [16]:
pd.set_option("display.max_columns",None)
final_df

,event_id,event_type,partition_ab,game_id,event_timestamp,session_id,user_id,bullet_id,room_id,scene_id,bullet_level,killed,currency_type,bet,payout,profit,prev_balance,curr_balance,created_at,processed_at,fish_species,fish_value,multiplier,left_hp,killed_th,killed_det,rtp_th,rtp_det,platform_id,op_code,fish_id,device_type,ip,record_insert_timestamp
0,71178dc7-f241-42fd-b7fb-2e2e92a4061a,bullet-hit,"[""wytsuj-fothap-5Qixda""]",FM01,2025-08-17 20:06:42.618,f75dee7c-f06e-4a9a-82f6-dd46eed4393d,10100017160,1406730984847314944,fd49b4d8-d8aa-4f41-9079-259acbecb7b9,1406730740520718336,1,0,CNY,2.000,0.000,-2.000,1848.150,1846.150,2025-08-17 20:06:43,2025-08-17 20:06:43,10,130,2.000,0.910232,0.007692,0.907068,0.97,0.222329,1,T07,1406730740562661441,1,36.158.50.158,2025-08-17 21:09:05.745941
1,1f93ece7-8022-4332-bdf8-23398d19b09e,bullet-hit,"[""wytsuj-fothap-5Qixda""]",FM01,2025-08-17 12:42:06.204,d75399cf-a8f7-4901-b77c-110358b0043e,10100000480,1406619095865757696,3d323b25-fa38-484b-a3bf-fdcd14a7007a,1406618774795980800,1,0,CNY,1.000,0.000,-1.000,25544.000,25543.000,2025-08-17 12:42:06,2025-08-17 12:42:06,14,50,1.000,0.767176,0.020000,0.793532,0.97,0.367951,1,A58,1406618774833729644,1,183.195.56.181,2025-08-17 13:45:10.918130
2,be48070d-89e4-481c-86ae-8fb95e832d37,bullet-hit,"[""wytsuj-fothap-5Qixda""]",FM01,2025-08-17 00:00:14.249,7577946e-376b-4cb8-9db8-399a60fb0706,10100016721,1406427366030053376,2f8e6fa6-2efe-4f26-ace6-27ad9208ac42,1406426719553589248,2,0,CNY,2.000,0.000,-2.000,5367.170,5365.170,2025-08-17 00:00:14,2025-08-17 00:00:14,17,15,1.000,0.453491,0.133333,0.336817,0.97,0.747979,1,FA8,1406426719595532517,1,112.96.66.162,2025-08-17 01:06:16.667975
3,1c9ff5e0-df3f-4194-8127-bc74df4ff109,bullet-hit,"[""wytsuj-fothap-5Qixda""]",FM01,2025-08-17 00:27:16.442,b034b2df-ab11-49f4-a3ee-8757cc435cc9,10100015770,1406434169992253440,39aa1777-2f64-4d8f-a2c0-f650eb9af35c,1406434081186254848,1,0,CNY,1.000,0.000,-1.000,82.000,81.000,2025-08-17 00:27:16,2025-08-17 00:27:16,22,4,1.000,0.712294,0.250000,0.562202,0.97,0.122320,1,JO5,1406434081232392218,1,223.74.114.115,2025-08-17 01:30:13.541698
4,3eb6aa05-1b0f-475a-acd6-c7e49dbb7968,bullet-hit,"[""wytsuj-fothap-5Qixda""]",FM01,2025-08-17 20:06:43.015,f75dee7c-f06e-4a9a-82f6-dd46eed4393d,10100017160,1406730986512453632,fd49b4d8-d8aa-4f41-9079-259acbecb7b9,1406730740520718336,1,0,CNY,2.000,0.000,-2.000,1844.150,1842.150,2025-08-17 20:06:43,2025-08-17 20:06:43,10,130,2.000,0.891404,0.007692,0.232263,0.97,0.169436,1,T07,1406730740562661441,1,36.158.50.158,2025-08-17 21:09:05.745941
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9858634,e8e84f6c-98a4-4e75-bb3b-408769d18a71,bullet-hit,"[""wytsuj-fothap-5Qixda""]",FM01,2025-08-29 23:33:32.188,71dcd0e8-a6d0-4aef-b4b7-e663fb2df471,10100000694,1411131688781352960,e9452aa9-651c-49e5-b308-d4a9f4127425,1411131055164624896,1,0,CNY,2.000,0.000,-2.000,8.550,6.550,2025-08-29 23:33:32,2025-08-29 23:33:32,5,500,2.000,0.971776,0.002000,0.628646,0.97,0.157551,1,A58,1411131055177208399,1,113.73.156.22,2025-08-30 00:35:07.986525
9858635,ccb98ef3-1472-439e-80dd-a3e6c3698e25,bullet-hit,"[""wytsuj-fothap-5Qixda""]",FM01,2025-08-29 23:33:33.451,71dcd0e8-a6d0-4aef-b4b7-e663fb2df471,10100000694,1411131694078758912,e9452aa9-651c-49e5-b308-d4a9f4127425,1411131055164624896,1,0,CNY,2.000,0.000,-2.000,6.550,4.550,2025-08-29 23:33:33,2025-08-29 23:33:33,5,500,2.000,0.969638,0.002000,0.517136,0.97,0.169874,1,A58,1411131055177208399,1,113.73.156.22,2025-08-30 00:35:07.986525
9858636,73d33226-d8a2-4178-a45a-7d1b0789221f,bullet-hit,"[""wytsuj-fothap-5Qixda""]",FM01,2025-08-29 23:33:36.807,71dcd0e8-a6d0-4aef-b4b7-e663fb2df471,10100000694,1411131708154843136,e9452aa9-651c-49e5-b308-d4a9f4127425,1411131055164624896,1,0,CNY,2.000,0.000,-2.000,4.550,2.550,2025-08-29 23:33:37,2025-08-29 23:33:37,6,200,2.000,0.990219,0.005000,0.871192,0.97,0.766295,1,A58,1411131055177208055,1,113.73.156.22,2025-08-30 00:35:07.986525
9858637,bcb2b337-3231-45c5-aed1-c02526bcab66,bullet-hit,"[""wytsuj-fothap-5Qixda""]",FM01,2025-08-29 23:33:39.057,71dcd0e8-a6d0-4aef-b4b7-e663fb2df471,10100000694,1411131717587832832,e9452aa9-651c-49e5-b308-d4a9f4127425,1411131055164624896,1,0,CNY,2.000,0.000,-2.000,2.550,0.550,2025-08-29 23:33:39,2025-08-29 23:33:39,6,200,2.000,0.980534,0.005000,0.084369,0.97,0.548404,1,A58,1411131055177208055,1,113.73.156.22,2025-08-30 00:35:07.986525
9858638,8ebbe6a2-b137-4666-9f00-5719b335d473,bullet-hit,"[""wytsuj-fothap-5Qixda""]",FM01,2025-08-29 07:42:53.025,82622f0b-f913-4bb3-ac29-b0c372ce42b4,10100013420,1410892449191825408,369ef049-0f17-47b2-9530-53d77374d8ba,1410891402280964096,2,0,CNY,2.000,0.000,-2.000,1116.330,1114.330,2025-08-29 07:42:53,2025-08-29 07:42:53,1,1000,1.000,0.713108,0.002000,0.669302,0.97,0.192453,1,N23,1410891402297741851,1,221.7.7.46,2025-08-29 08:45:05.948905

In [12]:
import os
import glob
import pandas as pd
import concurrent.futures

BASE_PATH = "./FM01player/"   

# 递归查找所有 parquet 文件
parquet_files = glob.glob(os.path.join(BASE_PATH, "*.parquet"), recursive=True)
print(f"找到 {len(parquet_files)} 个 parquet 文件")

def load_parquet(file_path):
    """读取单个 parquet 文件"""
    try:
        return pd.read_parquet(file_path)
    except Exception as e:
        print(f"❌ 读取失败 {file_path}: {e}")
        return pd.DataFrame()

# 多线程读取
dfs = []
with concurrent.futures.ThreadPoolExecutor(max_workers=8) as executor:  # 8 个线程，可调
    futures = {executor.submit(load_parquet, f): f for f in parquet_files}
    for future in concurrent.futures.as_completed(futures):
        df = future.result()
        if not df.empty:
            dfs.append(df)

# 合并成一个 DataFrame
player_df = pd.concat(dfs, ignore_index=True)

print(f"合并完成，DataFrame 形状: {player_df.shape}")

找到 1 个 parquet 文件
合并完成，DataFrame 形状: (31357, 12)

In [13]:
player_df

,id,user_id,account_type,user_name,nick_name,avatar,platform_id,is_ban,salt,created_at,updated_at,op_code
0,2,10100000002,1,TSTFHTESTCNY01,FHTESTCNY01,https://d2pdak3l0a4hnl.cloudfront.net/asset_v1...,1,False,gCqvafDl,2025-05-15 18:39:24,2025-05-16 18:30:53,TST
1,62,10100000062,1,B26B26_PBCCTV03,静静太阳天,https://d2pdak3l0a4hnl.cloudfront.net/asset_v1...,1,False,XShuPdlz,2025-05-26 17:15:51,2025-05-26 18:22:11,B26
2,64,10100000064,1,A23s0522941usdt,s0522941usdt,https://d2pdak3l0a4hnl.cloudfront.net/asset_v1...,1,False,fdTogDpj,2025-05-27 00:22:22,2025-05-27 00:22:31,A23
3,65,10100000065,1,A58A58AGIN41872,A58AGIN41872,https://d2pdak3l0a4hnl.cloudfront.net/asset_v1...,1,False,ifVUpjWQ,2025-05-27 01:37:44,2025-05-27 01:50:52,A58
4,79,10100000079,1,A5802j9lidenghai,02j9lidenghai,https://d2pdak3l0a4hnl.cloudfront.net/asset_v1...,1,False,fqAiaZjD,2025-05-27 05:25:44,2025-05-27 05:26:06,A58
...,...,...,...,...,...,...,...,...,...,...,...,...
31352,21,10100000021,1,B26FrankHGc,FrankHGc,,1,False,HopqdCoM,2025-05-20 22:40:59,2025-09-23 22:32:55,B26
31353,24444,10100024444,1,LA4yy_y289879,yy_y289879,,1,False,ymyIapuZ,2025-09-03 08:57:34,2025-09-23 22:39:26,LA4
31354,10165,10100010165,1,LG7x1aoqi,x1aoqi,,1,False,BGAwDnHU,2025-08-01 16:02:02,2025-09-23 23:03:24,LG7
31355,31358,10100031358,1,FW2wxg0001b83d,wxg0001b83d,,1,False,iSsTTmaB,2025-09-23 23:12:48,2025-09-23 23:12:48,FW2
31356,31359,10100031359,1,DB2verljm123456_f,verljm123456_f,,1,False,sHiyjlfj,2025-09-23 23:25:36,2025-09-23 23:26:56,DB2